<a href="https://colab.research.google.com/github/Ragurammurali/numpy-exercise/blob/main/numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
list=[1,9,8,3]
print(list)

[1, 9, 8, 3]


In [ ]:
numpy_array=np.array(list)
numpy_array

array([1, 9, 8, 3])

In [ ]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
x=numpy_array+10
print(x)

[11 19 18 13]


In [ ]:
a=np.array([1,2,3])
print(a.shape)
print(a.dtype)

(3,)
int64


In [ ]:
b=np.array([1.5,2.6])
print(b.dtype)

float64


In [ ]:
c=np.array([(1,2,3),
           (4,5,6)])
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
d=np.array([(1,2),(3,4),(5,6)])
print(d.shape)

(3, 2)


In [ ]:
import numpy as np
x=np.zeros((2,2), dtype=np.int16)
print(x)

[[0 0]
 [0 0]]


In [ ]:
import numpy as np
np.ones((1,2,3), dtype=np.int16)	

array([[[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [ ]:
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
e.flatten()


array([1, 2, 3, 4, 5, 6])

In [ ]:
## Horitzontal Stack
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [ ]:
## Vertical Stack
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


In [ ]:
## Generate random nmber from normal distribution
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)			


[5.10019188 5.35860811 5.27661734 5.12828143 5.01591017 5.25499173
 5.7153512  5.08982572 4.32305995 4.50545401]


In [ ]:
A = np.matrix(np.ones((4,4)))		
np.array(A)[2]=2  #immutable
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


In [ ]:
np.arange(1, 11)	

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1, 14, 4)	

array([ 1,  5,  9, 13])

In [ ]:
import numpy as np
np.linspace(1.0, 10.0, num=20)


array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])